### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by mamal72** [mohebifar/react-native-ximage#1]
Hey. I think you forgot to import a polyfill for `Symbol`. I recommend you to import [babel-polyfill](http://babeljs.io/docs/usage/polyfill). I'll push a PR for it. I hope you to be OK with it.

P.S: I was going to write such module but I didn't tried. Anyway, thanks for your effort for making react and react-native community better. 👍

**Comment by hbsndg** [comment]
I also this problem,how to solve the problem??

**Comment by mamal72** [comment]
@hbsndg This component is deprecated. Please check [README](https://github.com/mohebifar/react-native-ximage#deprecated) file.
